name: 'CI'

on:
  push:
    branches: ['main']
  pull_request:

env:
  COMPOSER_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

jobs:
  php-cs-fixer:
    name: 'PHP-CS-Fixer'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.1'
          ini-values: 'memory_limit=-1'
          tools: 'php-cs-fixer'
          coverage: 'none'
      - name: 'Run PHP-CS-Fixer analysis'
        run: 'php-cs-fixer fix --dry-run --diff --ansi'

  phpstan:
    name: 'PHPStan'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.2'
          tools: 'composer'
          coverage: 'none'
          ini-values: 'memory_limit=-1'
      - uses: 'ramsey/composer-install@v3'
      - name: 'Cache PHPStan results'
        uses: 'actions/cache@v2'
        with:
          path: '/tmp/phpstan'
          key: 'phpstan-php${{ matrix.php }}-${{ github.sha }}'
          restore-keys: |
            phpstan-php${{ matrix.php }}-
            phpstan-
        continue-on-error: true
      - name: 'Install PHPUnit'
        run: 'vendor/bin/simple-phpunit --version'
      - name: 'Run PHPStan analysis'
        run: './vendor/bin/phpstan analyse --no-interaction --no-progress --ansi'

  phpunit:
    name: 'PHPUnit'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        dependencies-version:
#          - 'lowest'
          - 'highest'
      fail-fast: false
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
          tools: 'composer'
          coverage: 'none'
          ini-values: 'memory_limit=-1'
      - uses: 'ramsey/composer-install@v3'
        with:
          dependency-versions: '${{ matrix.dependencies-version }}'
      - name: 'Install PHPUnit'
        run: 'vendor/bin/simple-phpunit --version'
      - name: 'Run PHPUnit tests'
        run: 'vendor/bin/simple-phpunit'
